### ISSUE TITLE
support letsencrypt

### ISSUE THREAD

**Issue by bbodenmiller** [sonatype/nxrm3-ha-repository#24]
with https://github.com/sonatype/nxrm3-helm-repository/tree/main/nexus-repository-manager we're able to enable letsencrypt with following. This does not appear possible with HA chart. Specifically ingress template does not configure TLS

```
ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.org/client-max-body-size: "0"
  enabled: true
  hostPath: /
  hostRepo: nexus.somedomain.com
  ingressClassName: nginx
  tls:
  - hosts:
    - nexus.somedomain.com
    secretName: nexus-local-tls
```
