### ISSUE TITLE
Support pre-existing kubernetes secrets

### ISSUE THREAD

**Issue by renesch-de** [sonatype/nxrm3-ha-repository#61]
Currently, two option exist for referencing the License-File and DB-/Admin-credentials:

1. Via the secrets-store.csi.x-k8s.io/v1 API.
2. As a Kubernetes secret, directly created by the Helm-Chart.

It would be helpful to introduce a third option where a pre-existing Kubernetes secret can be referenced. This would be beneficial when other Azure Key-Vault synchronization mechanisms are in use, like akv2k8s (https://akv2k8s.io/).

**Comment by snakebyte91** [comment]
We use the external secrets operator to manage our kubernetes secrets. The reference of existing secrets would help us.

**Comment by snakebyte91** [comment]
Workaround for pre-existing secrets:

```yaml
nameOverride: nexus-ha
secret:
  license:
    name: license.lic
    licenseSecret:
      mountPath: /etc/nexus-license/
statefulset:
  additionalVolumes:
    - name: nexus-pro-license
      secret:
        secretName: nexus-pro-license
  additionalVolumeMounts:
    - name: nexus-pro-license
      mountPath: /etc/nexus-license/
      readOnly: true
```

Create the secrets `nexus-ha-adminsecret` and `nexus-ha-dbsecret`. This could be done by a tool of your choice or manually. The prefix `nexus-ha` is taken from `nameOverride`.
