### ISSUE TITLE
Allow specifying `topologySpreadConstraints` on StatefulSet

### ISSUE THREAD

**Issue by vitorstone** [sonatype/nxrm3-ha-repository#75]
In my StatefulSet I want to be able to add this block of code:

```
topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app: nexus
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app: nexus
```

PS: The matchLabels part would be different but you get the gist.

The reason for that is because we've labeled our k8s nodes with `topology.kubernetes.io/zone` and `kubernetes.io/hostname` so that the pods can be created on different nodes and different zones, if possible.
